### ISSUE TITLE
Bug with slovak langage and gestion application

### ISSUE THREAD

**Issue by baimard** [nextcloud/nextcloud-l10n#586]
The translation in slovak langage of gestion cause an error in l10n translator in nextcloud, please refer to https://github.com/baimard/gestion/issues/320.

Error message sent by the server :

```
	<h3>Technické podrobnosti</h3>
	<ul>
		<li>Vzdialená adresa: 92.184.98.78</li>
		<li>ID požiadavky: CTrymg0dBsE9GkhvB3xt</li>
					<li>Typ: ValueError</li>
			<li>Kód: 0</li>
			<li>Správa: The arguments array must contain 1 items, 0 given</li>
			<li>Súbor: /var/www/html/lib/private/L10N/L10NString.php</li>
			<li>Riadok: 88</li>
			</ul>

			<br />
		<h3>Trasa</h3>
		<pre>#0 /var/www/html/lib/private/L10N/L10NString.php(88): vsprintf(&#039;V\xC3\xA1\xC5\xBEen\xC3\xA1/V\xC3\xA1\xC5\xBE...&#039;, Array)
#1 /var/www/html/lib/private/L10N/L10N.php(106): OC\L10N\L10NString-&gt;__toString()
#2 /var/www/html/lib/private/L10N/LazyL10N.php(52): OC\L10N\L10N-&gt;t(&#039;Dear,&#039;, Array)
#3 /var/www/html/custom_apps/gestion/templates/content/changelog.php(43): OC\L10N\LazyL10N-&gt;t(&#039;Dear,&#039;)
#4 /var/www/html/lib/private/Template/Base.php(180): include(&#039;/var/www/html/c...&#039;)
#5 /var/www/html/lib/private/legacy/OC_Template.php(229): OC\Template\Base-&gt;load(&#039;/var/www/html/c...&#039;, NULL)
#6 /var/www/html/custom_apps/gestion/templates/index.php(14): OC_Template-&gt;inc(&#039;content/changel...&#039;)
#7 /var/www/html/lib/private/Template/Base.php(180): include(&#039;/var/www/html/c...&#039;)
#8 /var/www/html/lib/private/Template/Base.php(150): OC\Template\Base-&gt;load(&#039;/var/www/html/c...&#039;, Array)
#9 /var/www/html/lib/private/legacy/OC_Template.php(181): OC\Template\Base-&gt;fetchPage(Array)
#10 /var/www/html/lib/public/AppFramework/Http/TemplateResponse.php(213): OC_Template-&gt;fetchPage(Array)
#11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(178): OCP\AppFramework\Http\TemplateResponse-&gt;render()
#12 /var/www/html/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher-&gt;dispatch(Object(OCA\Gestion\Controller\PageController), &#039;index&#039;)
#13 /var/www/html/lib/private/Route/Router.php(298): OC\AppFramework\App::main(&#039;OCA\\Gestion\\Con...&#039;, &#039;index&#039;, Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 /var/www/html/lib/base.php(1047): OC\Route\Router-&gt;match(&#039;/apps/gestion/&#039;)
#15 /var/www/html/index.php(36): OC::handleRequest()
#16 {main}

```

What's strange is that all others langage work. Could you help me ?

**Comment by susnux** [comment]
This is an issue with your translation string, the string contains a parameter while no parameters are expected.

I had a quick look, this translations are wrong (there is a `%` indicating a parameter while there should be none):

https://github.com/baimard/gestion/blob/1bb507abbb75ec4caa2f8e72eb1baca31a28ee54/l10n/sk.js#L71

and 

https://github.com/baimard/gestion/blob/1bb507abbb75ec4caa2f8e72eb1baca31a28ee54/l10n/sk.js#L278

---

But this is also not related to this project, as this is only about the javascript library, the backend l10n library is part of the server, maybe you want to open an issue because an error like this should probably handled more gracefully:
https://github.com/nextcloud/server/issues
